### ISSUE TITLE
Kerning issue in 3.0 Dev Branch

### ISSUE THREAD

**Issue by SuperWomble** [lvnyk/BezierString#3]
Firstly, this is such a great example of coding. Thank you for all your work on this. 

I've run across an issue with kerning on the attributed string. Kerning (or spacing) is taking place, but it appears that the spacing calculations don't take kerning in to account properly.

Here's an example of an arc path with no `NSKernAttributeName` applied. For clarity, I've set the alignment to the right:

![no kerning](https://cloud.githubusercontent.com/assets/20920689/18977502/0e0d581e-86fa-11e6-9d8f-2a78401ff415.png)

As you can see, the results are as expected. 

If I add a kerning value:

```
string.addAttribute(NSKernAttributeName,
        value: 6,
        range: NSRange(location: 0, length: string.length))
```

The result is:

![with kerning](https://cloud.githubusercontent.com/assets/20920689/18977544/634f85e0-86fa-11e6-8df5-9f73fdd65885.png)

Note the distance from the right edge of the arc path, to the "E" character.  That gap increases as the size of the kerning value increases.  

This also happens with left and center alignments, but is harder to notice.

BTW, increasing the kerning value will also distort the character's individual rotations. I'm not sure if this is related to the above issue. Here's an exaggerated example, where the kerning has been pushed up to 20 points:

![exaggerated](https://cloud.githubusercontent.com/assets/20920689/18977638/2e54ebb8-86fb-11e6-96aa-48d61ff1e446.png)

Big cheers, and thanks again. 

[an update, several hours later...]

It appears that using kerning with an NSAttributedString will cause the string to have extra space appended to it, for the kerning of the last character.  Investigation ways to fix/remove this.

[**updated again**]

OK, please accept my apologies. I'm sorry for wasting your time. The spacing issue was caused by me not knowing about NSString's kerning behaviour.  When kerning is applied to the entire string, the last character is also given extra space for kerning, even though it may not need/want it.  The solution was to only apply the kerning attribute to `string.length - 1`

The issue of distorted rotations of characters when using kerning is still there, however.  Cheers.

**Comment by lvnyk** [comment]
Nice research, thanks :)

When positioning each of the glyphs on a curve, a bounding box of that character is used to basically determine how wide it is and in turn how far along the curve it should be positioned. The center of the box is then placed on the curve and rotated accordingly, and a glyph is rendered.
The bounding box is generated using the assumption that the  glyph width equals it's advance. When kerning is applied, this effectively adds padding to the glyph in the direction of writing, and while the bounding box is positioned correctly, it's dimensions are wrong and glyph positions and rotations are off. 

![wrong boxes](https://cloud.githubusercontent.com/assets/9917622/19013563/834ac17c-87d4-11e6-9572-5416658048e8.png)

Taking kerning into the account fixes this issue

![fixed boxes](https://cloud.githubusercontent.com/assets/9917622/19013568/ae5b24b0-87d4-11e6-922d-53e1d93ff94b.png)

As you've already discovered, coretext apparently doesn't remove kerning padding for the last glyph and takes it into the account when aligning strings, so it's probably best if the behavior isn't any different here, however inconvenient as it might be.

Further adjustments of this sort might be needed for handling some paragraph style attributes, but paragraph style probably isn't a realistic use case when rendering a single line of text.

**Comment by SuperWomble** [comment]
Your commits work as advertised. Well done. You are awesome. 👍
